id: IEAC99049
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-30T21:46:58.136789'
last_modified: '2022-05-30T21:46:58.136795'
parser: null
source_metadata:
  title: Jetsün Mingyur Paldrön
  language: bo
  description: 'Texts by and about Jetsün Mingyur Paldrön (rje btsun mi ''gyur dpal
    sgron, 1699–1769), daughter of Minling Terchen Gyurme Dorje:'
  volume:
    f9E41:
      title: Mindrolling Lineage Prayer
      base_file: f9E41.txt
      order: 1
      parent: Lineage Prayers
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
